version: "3.8"
services:
  nodeserver:
    build: .
    container_name: nodeserver
    hostname: nodeserver
    ports:
      - "3003:3003"
    working_dir: /usr/src/app
    command: node app.js
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongodb
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - nodeserver
